-- MySQL Script generated by MySQL Workbench
-- dom 22 abr 2018 19:49:19 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestisport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestisport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestisport` DEFAULT CHARACTER SET utf8 ;
USE `gestisport` ;

-- -----------------------------------------------------
-- Table `gestisport`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NULL,
  `role` VARCHAR(191) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestisport`.`tournament_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`tournament_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name`  NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestisport`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`sports` (
  `id` INT NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`tournaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_type_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `name` VARCHAR(191) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sport_id_idx` (`sport_id` ASC),
  INDEX `fk_admin_id_idx` (`admin_id` ASC),
  INDEX `fk_tournament_type_idx` (`tournament_type_id` ASC),
  CONSTRAINT `fk_tournament_type`
    FOREIGN KEY (`tournament_type_id`)
    REFERENCES `gestisport`.`tournament_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sport_id`
    FOREIGN KEY (`sport_id`)
    REFERENCES `gestisport`.`sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `gestisport`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_composition_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  `name` VARCHAR(191) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `team_composition_id_UNIQUE` (`team_composition_id` ASC),
  INDEX `fk_team_sport_idx` (`sport_id` ASC),
  CONSTRAINT `fk_team_sport`
    FOREIGN KEY (`sport_id`)
    REFERENCES `gestisport`.`sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_id` INT NOT NULL,
  `team_local_id` INT NOT NULL,
  `team_visitor_id` INT NOT NULL,
  `match_result_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matches_team_local_idx` (`team_local_id` ASC),
  INDEX `fk_matches_team_visitor_idx` (`team_visitor_id` ASC),
  INDEX `fk_tournament_idx` (`tournament_id` ASC),
  CONSTRAINT `fk_matches_team_local`
    FOREIGN KEY (`team_local_id`)
    REFERENCES `gestisport`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_team_visitor`
    FOREIGN KEY (`team_visitor_id`)
    REFERENCES `gestisport`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `gestisport`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestisport`.`team_compositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`team_compositions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_compositions_team_id_idx` (`team_id` ASC),
  INDEX `fk_team_compositions_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_team_compositions_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `gestisport`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_compositions_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `gestisport`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`league_clasifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`league_clasifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `points` INT NULL,
  `goals_scored` INT NULL,
  `goals_against` INT NULL,
  `goals_difference` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tournament_id_idx` (`tournament_id` ASC),
  INDEX `fk_team_id_idx` (`team_id` ASC),
  CONSTRAINT `fk_tournament_id`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `gestisport`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `gestisport`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`cup_rounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`cup_rounds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `round_name` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`cup_clasifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`cup_clasifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `cup_round_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tournament_id_idx` (`tournament_id` ASC),
  INDEX `fk_cup_round_id_idx` (`cup_round_id` ASC),
  INDEX `fk_team_id_idx` (`team_id` ASC),
  CONSTRAINT `fk_tournament_id`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `gestisport`.`tournaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `gestisport`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cup_round_id`
    FOREIGN KEY (`cup_round_id`)
    REFERENCES `gestisport`.`cup_rounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`match_scorers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`match_scorers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `minute` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_match_id_idx` (`match_id` ASC),
  CONSTRAINT `fk_match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `gestisport`.`matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`padel_match_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`padel_match_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT NOT NULL,
  `local_team_first_set_points` INT NULL,
  `visitor_team_first_set_points` INT NULL,
  `local_team_second_set_points` INT NULL,
  `visitor_team_second_set_points` INT NULL,
  `local_team_third_set_points` INT NULL,
  `visitor_team_third_set_points` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_match_id_idx` (`match_id` ASC),
  CONSTRAINT `fk_match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `gestisport`.`matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `gestisport`.`football_match_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestisport`.`football_match_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT NOT NULL,
  `local_team_goals` INT NULL DEFAULT 0,
  `viistor_team_goals` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_football_match_id_idx` (`match_id` ASC),
  CONSTRAINT `fk_football_match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `gestisport`.`matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gestisport`.`tournament_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestisport`;
INSERT INTO `gestisport`.`tournament_types` (`id`, `name`) VALUES (1, league);
INSERT INTO `gestisport`.`tournament_types` (`id`, `name`) VALUES (2, cup);
INSERT INTO `gestisport`.`tournament_types` (`id`, `name`) VALUES (3, mixed);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestisport`.`sports`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestisport`;
INSERT INTO `gestisport`.`sports` (`id`, `name`) VALUES (1, 'futsal');
INSERT INTO `gestisport`.`sports` (`id`, `name`) VALUES (2, 'padel');
INSERT INTO `gestisport`.`sports` (`id`, `name`) VALUES (3, 'fut7');
INSERT INTO `gestisport`.`sports` (`id`, `name`) VALUES (4, 'fut11');

COMMIT;

